config/routes.rb
Rails.application.routes.draw do

  resources :questions

end

app/models/question.rb
class Question < ActiveRecord::Base

	validates :year, presence: true, length: { maximum: 4 }
	validates :area, presence: true
	validates :number, presence: true, length: { maximum: 3 }
	validates :enunciation, presence: true
	validates :reference, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

	def index
	end

	def new
		@question = Question.new
	end

	def create
		@question = Question.new(question_params)
		if @question.save
			flash[:success] = "Questão cadastrada com sucesso!"
		else
			render 'new'
		end
	end

	def edit
		@question = Question.find(params[:id])
	end

	def update
		@question = Question.find(params[:id])
		if @question.update_attributes(question_params)
			flash[:success] = "Questão atualizada com sucesso!"
		else
			render 'edit'
		end
	end

	def show
		@question = Question.find(params[:id])
	end

	def destroy
		@question = Question.find(params[:id])
		@question.destroy
		flash[:success] = "Questão deletada com sucesso!"
		render 'index'
	end

	private

	def question_params
		params.require(:question).permit(:year,:area,:number,:enunciation,:reference,:image)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/question_helper.rb
module QuestionHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>EnemAmigo</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/question/delete.html.erb
<h1>Question#delete</h1>
<p>Find me in app/views/question/delete.html.erb</p>

app/views/question/edit.html.erb
<h1>Question#edit</h1>
<p>Find me in app/views/question/edit.html.erb</p>

app/views/question/index.html.erb
<h1> Index of questions </h1>

<% if !@question.blank? %>
	<% @question.each do |q| %>
		puts q
	<% end %>
<% else %>
	<h3> It seems that you haven't created any question :(</h3>
<% end %>

<%= link_to 'Create Question', question_new_path %>

app/views/question/new.html.erb
<h1>Question#new</h1>
<p>Find me in app/views/question/new.html.erb</p>

<%= form_for @question do |f| %>
	<%= f.label :year %>
	<%= f.label :year %>

	<%= f.label :area %>
	<%= f.label :area %>
	
	<%= f.submit  %>
<% end %>

app/views/question/show.html.erb
<h1>Question#show</h1>
<p>Find me in app/views/question/show.html.erb</p>